# itk-version: 3.0.0
version: "3"

networks:
  frontend:
    external: true

services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - frontend
    ports:
      - '8080'
    volumes:
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
#      HTTPS config - uncomment to enable redirect from :80 to :443
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  shellcheck:
    image: koalaman/shellcheck-alpine
    working_dir: /app
    volumes:
      - .:/app
